import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {known,number,scale,health,series,heatmap,chartBounds,operationNotice,activityDetails,detailText,chartHoverIndex} from '../web/presentation.js';
test('unknown is never zero',()=>{for(const value of [null,undefined,NaN,'12']){assert.equal(known(value),false);assert.equal(number(value),'—');assert.equal(scale(value,true),null);}assert.equal(number(0),'0');assert.equal(scale(4,true),100);});
test('connection failure preserves saved view semantics',()=>{const data={available:true};assert.equal(health(data,100,200,false).stale,false);assert.equal(health(data,100,30000,false).stale,true);assert.equal(health(data,100,200,true).stale,true);assert.equal(health(null,100,200).text,'Runway unavailable');});
test('heatmap uses UTC weeks and correct daily/weekly/cumulative totals',()=>{const now=Date.parse('2026-10-02T12:00:00Z'),days=[{date:'2026-09-28',tokens:10},{date:'2026-09-29',tokens:30}];assert.equal(heatmap(days,'Daily',now).flat().find(d=>d.date==='2026-09-29').value,30);assert.equal(heatmap(days,'Weekly',now).at(-1)[0].value,40);assert.equal(heatmap(days,'Cumulative',now).at(-1)[0].value,40);});
test('native percentage scale and graph historical zoom',()=>{assert.deepEqual(chartBounds([2,3],4),[0,4]);const [low,high]=chartBounds([2,3]);assert.ok(low>0&&high>3);assert.deepEqual(chartBounds([null]),[0,1]);});
test('weighted usage and missing days stay distinct',()=>{const now=Date.parse('2026-10-02T12:00:00Z'),accounts=[{capacityUnits:4,usage:[{date:'2026-10-02',features:[{name:'task',value:50}]}]},{capacityUnits:1,usage:[{date:'2026-10-02',features:[{name:'task',value:10}]}]}];const s=series(accounts,'usage','features',7,now);assert.equal(s.total,42);assert.equal(s.rows.length,1);assert.equal(s.rows[0].values.Tasks,42);});
test('messages sum unweighted and preserve unrepresented Other',()=>{const now=Date.parse('2026-10-02T12:00:00Z');const s=series([{messages:[{date:'2026-10-02',total:10,models:[{name:'Sol',value:8}]}]},{messages:[{date:'2026-10-02',total:5,models:[{name:'Sol',value:4}]}]}],'messages','models',7,now);assert.equal(s.total,15);assert.equal(s.rows[0].values.Other,3);});
test('curated Swift export parity and secret exclusion',()=>{const fixture=JSON.parse(fs.readFileSync(process.env.RUNWAY_HUB_FIXTURE||'/private/tmp/runway-hub-fixture.json','utf8'));assert.equal(fixture.version,1);const report=fixture.overview;assert.equal(scale(report.total,true),125);assert.equal(fixture.history.stats['Lifetime tokens'],'1M');const a=fixture.analytics.accounts;const usage=series(a,'usage','features',30,fixture.generatedAt*1000);assert.ok(Math.abs(usage.total-12)<1e-9);const messages=series(a,'messages','models',7,fixture.generatedAt*1000);assert.equal(messages.total,160);assert.equal(messages.rows[0].values.Other,20);assert.ok(!JSON.stringify(fixture).includes('NEVER_EXPORT'));});

test('weekly and cumulative heatmaps use native bottom-filled bars, including the current week',()=>{const now=Date.parse('2026-10-02T12:00:00Z'),days=[{date:'2026-09-21',tokens:10},{date:'2026-09-28',tokens:30}];const weekly=heatmap(days,'Weekly',now);assert.deepEqual(weekly.at(-2).map(d=>d.level),[0,0,0,0,4,4,4]);assert.deepEqual(weekly.at(-1).map(d=>d.level),[4,4,4,4,4,4,4]);assert.ok(weekly.at(-1).every(d=>!d.hidden));const cumulative=heatmap(days,'Cumulative',now);assert.deepEqual(cumulative.at(-2).map(d=>d.level),[0,0,0,0,0,4,4]);assert.deepEqual(cumulative.at(-1).map(d=>d.level),[4,4,4,4,4,4,4]);const daily=heatmap(days,'Daily',now).flat();assert.equal(daily.find(d=>d.date==='2026-09-21').level,2);assert.equal(daily.find(d=>d.date==='2026-09-28').level,4);assert.equal(daily.at(-1).hidden,true);});

test('completed and cancelled operations do not produce a banner, including a freshly completed receipt',()=>{for(const state of ['completed','cancelled'])assert.equal(operationNotice({operations:[{state,message:'Native operation completed.',finishedAt:99}]},100),null);});
test('operation progress, failures and recovery still surface without receipt IDs',()=>{assert.deepEqual(operationNotice({status:{recoveryPending:true},operations:[]},100),{source:'recovery',message:'A switch needs recovery. Open native Runway or use Recover Switch in Settings.'});assert.equal(operationNotice({status:{loginBusy:true,loginMessage:'Preflight'},operations:[{id:'PRIVATE_RECEIPT',state:'running',message:'Switching'}]},100).message,'Switching Preflight');assert.equal(operationNotice({operations:[{state:'failed',message:'Needs attention',finishedAt:99}]},100).message,'Needs attention');assert.equal(operationNotice({operations:[{state:'failed',finishedAt:1}]},100),null);assert.equal(operationNotice({operations:[{state:'interrupted',message:'Recover',finishedAt:99}]},100).message,'Recover');});
test('every activity tooltip uses the actual daily series and matching units and totals',()=>{for(const type of ['usage','messages','plugins','skills']){const detail=activityDetails('2026-10-02',{Alpha:1.25,Beta:2.5},type);assert.deepEqual(detail.rows.map(r=>r.label),['Alpha','Beta']);const text=detailText(detail);assert.ok(text.startsWith('2026-10-02'));assert.ok(text.includes('Daily total:'));if(type==='usage'){assert.equal(detail.rows[0].value,'1.25%');assert.equal(detail.caption,'Daily total: 3.75% of limit');}else assert.ok(detail.caption.endsWith(type==='messages'?' messages':' calls'));}const missing=activityDetails('2026-10-02',{Known:2,Unknown:null},'usage');assert.equal(missing.rows[1].value,'—');assert.equal(missing.caption,'Daily total: —');});

test('reset snapping wins over dense readings within a fixed pixel distance at every plot scale',()=>{for(const secondsPerPixel of [.1,10,1200]){const times=[0,48,49,50,51,52,100].map(v=>v*secondsPerPixel),reset=50*secondsPerPixel;assert.equal(chartHoverIndex(times,[reset],49*secondsPerPixel,secondsPerPixel),3);assert.equal(chartHoverIndex(times,[reset],51*secondsPerPixel,secondsPerPixel),3);assert.equal(chartHoverIndex(times,[reset],38*secondsPerPixel,secondsPerPixel),3);assert.equal(chartHoverIndex(times,[reset],37.9*secondsPerPixel,secondsPerPixel),1);assert.equal(chartHoverIndex(times,[],49*secondsPerPixel,secondsPerPixel),2);}});
test('reset snapping selects the closest visible reset and ignores excluded reset times',()=>{const times=[10,20,30,40,50];assert.equal(chartHoverIndex(times,[20,40],31,1),3);assert.equal(chartHoverIndex(times,[20,40],29,1),1);assert.equal(chartHoverIndex(times,[29,40],30,1),3);assert.equal(chartHoverIndex(times,[29],30,1),2);assert.equal(chartHoverIndex(times,[40,40],30,1),3);assert.equal(chartHoverIndex([],[],30,1),-1);assert.equal(chartHoverIndex(times,[20],NaN,1),-1);});
